/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package mmeijiu.com.retrofit.entity;

import android.os.Parcel;
import android.os.Parcelable;

import java.io.Serializable;

public class PUser implements Parcelable, Serializable {
	
	private String id;
	private String username;
	private String email;
	private String phone;
	private int gid;
	
    
    private long lastlogin_time;
    private long regtime;
    private String money;
    private String score;
    private String growth;
    
    private String credit;
    private String realname;
    private int sex;
    private String qq;
    private String tel;
    

    private String area_id;
    private String address;
    private String pic_url;
    private String area_address;
    private double latitude; // 维度

    private double longitude; // 经度

    private boolean is_phone_auth;
    private boolean is_person_auth;
    private boolean is_company_auth;


    private String category_id_2; // 车辆信息
    private String plate; // 车牌号
    private String position; // 车辆地址



    
    public PUser(Parcel source) {

    }

    public PUser() {
    }
    
    public void writeToParcel(Parcel dest, int flags) {

    }

    public String getCategory_id_2() {
        return category_id_2;
    }

    public void setCategory_id_2(String category_id_2) {
        this.category_id_2 = category_id_2;
    }

    public String getPlate() {
        return plate;
    }

    public void setPlate(String plate) {
        this.plate = plate;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public boolean isIs_phone_auth() {
        return is_phone_auth;
    }

    public void setIs_phone_auth(boolean is_phone_auth) {
        this.is_phone_auth = is_phone_auth;
    }

    public boolean isIs_person_auth() {
        return is_person_auth;
    }

    public void setIs_person_auth(boolean is_person_auth) {
        this.is_person_auth = is_person_auth;
    }

    public boolean isIs_company_auth() {
        return is_company_auth;
    }

    public void setIs_company_auth(boolean is_company_auth) {
        this.is_company_auth = is_company_auth;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public String getArea_address() {
        return area_address;
    }

    public void setArea_address(String area_address) {
        this.area_address = area_address;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public int getGid() {
        return gid;
    }

    public void setGid(int gid) {
        this.gid = gid;
    }

    public long getLastlogin_time() {
        return lastlogin_time;
    }

    public void setLastlogin_time(long lastlogin_time) {
        this.lastlogin_time = lastlogin_time;
    }

    public long getRegtime() {
        return regtime;
    }

    public void setRegtime(long regtime) {
        this.regtime = regtime;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public String getGrowth() {
        return growth;
    }

    public void setGrowth(String growth) {
        this.growth = growth;
    }

    public String getCredit() {
        return credit;
    }

    public void setCredit(String credit) {
        this.credit = credit;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public int getSex() {
        return sex;
    }

    public void setSex(int sex) {
        this.sex = sex;
    }

    public String getQq() {
        return qq;
    }

    public void setQq(String qq) {
        this.qq = qq;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getArea_id() {
        return area_id;
    }

    public void setArea_id(String area_id) {
        this.area_id = area_id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPic_url() {
        return pic_url;
    }

    public void setPic_url(String pic_url) {
        this.pic_url = pic_url;
    }

    public static final Creator<PUser> CREATOR = new Creator<PUser>() {

		@Override
		public PUser createFromParcel(Parcel source) {
			return new PUser(source);
		}

		@Override
		public PUser[] newArray(int size) {
			return new PUser[size];
		}

	};


	@Override
	public int describeContents() {
		return 0;
	}

    @Override
    public String toString() {
        return "PUser{" +
                "id='" + id + '\'' +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", gid=" + gid +
                ", lastlogin_time=" + lastlogin_time +
                ", regtime=" + regtime +
                ", money='" + money + '\'' +
                ", score='" + score + '\'' +
                ", growth='" + growth + '\'' +
                ", credit='" + credit + '\'' +
                ", realname='" + realname + '\'' +
                ", sex=" + sex +
                ", qq='" + qq + '\'' +
                ", tel='" + tel + '\'' +
                ", area_id='" + area_id + '\'' +
                ", address='" + address + '\'' +
                ", pic_url='" + pic_url + '\'' +
                ", area_address='" + area_address + '\'' +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", is_phone_auth=" + is_phone_auth +
                ", is_person_auth=" + is_person_auth +
                ", is_company_auth=" + is_company_auth +
                ", category_id_2='" + category_id_2 + '\'' +
                ", plate='" + plate + '\'' +
                ", position='" + position + '\'' +
                '}';
    }
}
